services:
  mysql:
    image: mysql:8.4
    container_name: pawsitter-mysql

    environment:
      MYSQL_DATABASE: pawsitter
      MYSQL_USER: pawsitter
      MYSQL_PASSWORD: pawsitter_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - pawsitter-mysql-data:/var/lib/mysql

volumes:
  pawsitter-mysql-data: