spring.application.name=pawsitter
server.port=${SERVER_PORT:3400}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pawsitter}
spring.datasource.username=${DB_USERNAME:pawsitter}
spring.datasource.password=${DB_PASSWORD:pawsitter_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true