package lv.pawsitter.dto;


import lv.pawsitter.entity.OwnerProfile;
import lv.pawsitter.entity.SitterProfile;
import lv.pawsitter.model.RoleType;

import java.time.LocalDateTime;

/**
 * Data Transfer Object representing a user in API responses.
 * Contains public, non-sensitive user information such as ID, email, phone number,
 * role, and date of creation.
 *
 * <p>This DTO is used to expose user data to clients without revealing internal
 * fields such as passwords, authentication metadata, or other security‑sensitive
 * information stored in the domain model.</p>
 *
 * <p>The DTO is typically returned in endpoints related to user management,
 * authentication, profile retrieval, sitter/owner matching, and administrative
 * dashboards.</p>
 *
 * <p>All fields are immutable due to the use of Java {@code record}, ensuring
 * safe and predictable serialization in REST responses.</p>
 */
public record UserDTO(

        /**
         * Unique identifier of the user.
         * <p>Generated by the persistence layer and guaranteed to be stable.</p>
         */
        Long id,

        /**
         * Phone number associated with the user.
         * <p>Used for contact, verification, or notification purposes.
         * The DTO does not enforce formatting; normalization is handled elsewhere.</p>
         */
        String phoneNumber,

        /**
         * Email address of the user.
         * <p>Always stored and returned in lowercase to ensure consistent
         * comparisons and prevent case‑sensitive mismatches.</p>
         */
        String email,

        /**
         * Role assigned to the user (e.g., USER, SITTER, ADMIN).
         * <p>Determines the user's permissions and access level within the system.</p>
         */
        RoleType role,

        /**
         * Timestamp indicating when the user account was created.
         * <p>Returned as a {@link LocalDateTime}. The system stores timestamps in UTC
         * unless configured otherwise.</p>
         */
        LocalDateTime createdAt
) {
}